### ISSUE TITLE
Replace pytz with native zoneinfo module

### ISSUE THREAD

**Issue by BjoernPetersen** [woog-life/tweeter#9]

**Comment by torbencarstens** [comment]
https://docs.python.org/3/library/zoneinfo.html

Haven't used it yet, seems much simpler than the pytz interface though (at least at first glance).

**Comment by BjoernPetersen** [comment]
Yes, it also doesn't break Python's timezone model: https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html
